language: python
python:
- "3.6"
- "3.7"
dist: xenial
install:
- pip install --upgrade --pre poetry
- mkdir -p ~/.config/pypoetry
- poetry config settings.virtualenvs.create false
- poetry export --dev --format requirements.txt
- pip install -r requirements.txt
script:
- pylint fs/googledrivefs/
- pylint tests/
- pytest
after_success:
- coveralls
