language: python
python:
# - "3.6"
# - "3.7"
- "3.8"
dist: xenial
install:
- pip install poetry
- poetry install
script:
- pylint fs/googledrivefs/ tests/
# gitlab CI timeout seems to be 50 minutes/3000 seconds
- pytest --timeout=2700
after_success:
- coveralls
