language: python
python:
- "3.6"
- "3.7"
dist: xenial
install:
- pip install fs google-api-python-client google-auth pylint
script:
- pylint fs/googledrivefs/
- pylint tests/
after_success:
- coveralls
